import type { Dispatch, SetStateAction } from 'react';
import type { GitLabDiscovery, GitLabSettings, GitLabTestResult } from '../../lib/connectors';
import type { EventTransport, HookScope } from './support';

export interface GitLabWizardViewModel {
  mode: 'connect' | 'edit';
  initialSettings?: Partial<GitLabSettings>;
  credentialConfigured: boolean;
  step: number;
  setStep: Dispatch<SetStateAction<number>>;
  dataSourceId?: string;
  dataSourceName: string;
  setDataSourceName: Dispatch<SetStateAction<string>>;
  baseUrl: string;
  setBaseUrl: Dispatch<SetStateAction<string>>;
  groupPath: string;
  setGroupPath: Dispatch<SetStateAction<string>>;
  credential: string;
  setCredential: Dispatch<SetStateAction<string>>;
  discovery: GitLabDiscovery | null;
  eventTransport: EventTransport;
  hookScope: HookScope;
  setHookScope: Dispatch<SetStateAction<HookScope>>;
  managedProjects: boolean;
  setManagedProjects: Dispatch<SetStateAction<boolean>>;
  deliveryUrl: string;
  setDeliveryUrl: Dispatch<SetStateAction<string>>;
  webhookSigningToken: string;
  setWebhookSigningToken: Dispatch<SetStateAction<string>>;
  relayStatus?: 'connected' | 'stopped' | 'failed';
  busy: boolean;
  submitted: boolean;
  error: string;
  result: GitLabTestResult | null;
  sampleProjects: GitLabDiscovery['projects'];
  legacy: boolean;
  signedWebhooksSupported: boolean;
  canConfigureSignedWebhooks: boolean;
  eventSetupUnavailable: boolean;
  chooseEventTransport: (transport: EventTransport) => void;
  discover: () => void;
  reviewEvents: () => void;
  saveAndVerify: () => void;
  eventEndpoint: string;
  providerWebhookUrl: string;
  webhookInstallCommand: string;
  webhookName: string;
  onClose: () => void;
}
