#!/usr/bin/env bun
/**
 * Generate the documentation blocks that are derived from source, and fail the build when a
 * committed block no longer matches.
 *
 * Four facts in this repo drifted because they were maintained by hand in more than one file: the
 * workspace layout, the CI gate list, each connector's tool inventory, and the dashboard menu. All
 * four are derivable, so they are derived here instead. Prose that states one of them is generated
 * between markers or included with `--8<--`; the `--check` mode is a CI gate.
 *
 * The judgement a reader needs — what a workspace is *for*, what a gate is *protecting* — cannot be
 * derived, so it lives in `notes.ts` keyed by the identity discovered here. A workspace with no note,
 * or a note for a workspace that no longer exists, fails rather than shipping a half-written table.
 *
 * Connector tools are enumerated through the real registration path: the catalog's factory is called
 * with a stub config and the returned `tools()` array is read. No network, and no second list to
 * keep in step. Every connector outside `TOOLLESS_CONNECTORS` must enumerate at least one tool, and
 * a connector's declared shapes must not enumerate the same set, so a refactor that broke
 * enumeration fails here instead of publishing an empty or duplicated table.
 *
 * Run: `bun run docs:gen`  ·  Check: `bun run docs:gen --check`
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PANELS } from '../../apps/dashboard/src/lib/panels';
import { CONNECTOR_DEFINITIONS } from '../../packages/connectors/src/catalog';
import { SETTING_KEYS } from '../../packages/platform-settings/src/index';
import {
  CI_GATE_NOTES,
  CONNECTOR_SHAPES,
  DASHBOARD_PANEL_NOTES,
  MIN_TOTAL_CONNECTOR_TOOLS,
  PLATFORM_SETTING_NOTES,
  TOOLLESS_CONNECTORS,
  WORKSPACE_NOTES,
} from './notes';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const BANNER = '<!-- Generated by scripts/docs/gen.ts. Run `bun run docs:gen`. Do not edit. -->';

const problems: string[] = [];

function fail(message: string): void {
  problems.push(message);
}

/** Escapes the pipe and newline characters that would otherwise break a Markdown table cell. */
function cell(value: string): string {
  return value
    .replaceAll('|', '\\|')
    .replaceAll(/\s*\n\s*/g, ' ')
    .trim();
}

/** True when a note carries no usable prose, directly or in any of its fields. */
function blank(note: unknown): boolean {
  if (typeof note === 'string') return note.trim() === '';
  if (note && typeof note === 'object') {
    const fields = Object.values(note);
    // A fieldless object carries no prose either, and would otherwise reach cell(undefined).
    return fields.length === 0 || fields.some((f) => typeof f !== 'string' || f.trim() === '');
  }
  return true;
}

/**
 * Reports notes that are missing, orphaned, or empty.
 *
 * Emptiness is checked here rather than filtered at render time: a `''` note satisfies a key
 * comparison, so filtering it would drop the row from the table with nothing failing.
 *
 * @param kind - Noun used in the failure message.
 * @param discovered - Identities found in source.
 * @param notes - Hand-written notes, keyed by identity.
 */
function requireExactCoverage(
  kind: string,
  discovered: string[],
  notes: Record<string, unknown>,
): void {
  const annotated = Object.keys(notes);
  for (const id of discovered)
    if (!annotated.includes(id))
      fail(`${kind} "${id}" exists in source but has no note in notes.ts`);
  for (const id of annotated) {
    if (!discovered.includes(id)) {
      fail(`${kind} "${id}" has a note in notes.ts but no longer exists`);
      continue;
    }
    if (blank(notes[id])) fail(`${kind} "${id}" has an empty note in notes.ts`);
  }
}

// ---------------------------------------------------------------- workspaces

function discoverWorkspaces(): string[] {
  const globs: string[] = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).workspaces;
  const found: string[] = [];
  for (const glob of globs) {
    const parent = glob.replace(/\/\*$/, '');
    for (const entry of readdirSync(join(ROOT, parent), { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      if (existsSync(join(ROOT, parent, entry.name, 'package.json')))
        found.push(`${parent}/${entry.name}`);
    }
  }
  return found.sort();
}

function renderWorkspaces(paths: string[]): string {
  requireExactCoverage('workspace', paths, WORKSPACE_NOTES);
  const rows = paths.map((path) => `| \`${path}\` | ${cell(WORKSPACE_NOTES[path] ?? '')} |`);
  return [BANNER, '', '| Workspace | Responsibility |', '| --- | --- |', ...rows, ''].join('\n');
}

// ----------------------------------------------------------------- ci gates

/** Extracts the executable command lines from a `set -euo pipefail` style CI script. */
function scriptCommands(path: string): string[] {
  return readFileSync(join(ROOT, path), 'utf8')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#') && !line.startsWith('set '));
}

/** Scripts whose commands are gates, and scripts that deliberately are not. */
// Grouped lane by lane so each lane's gates stay together. Both providers run the lanes as
// parallel jobs, so this is a reading order, not an execution order.
const GATE_SCRIPTS = [
  'typecheck.sh',
  'lint.sh',
  'guards.sh',
  'test.sh',
  'test-ui.sh',
  'build.sh',
  'docs.sh',
];
const NON_GATE_SCRIPTS = [
  'bootstrap.sh',
  // The local aggregator. Its lines invoke the lane scripts, so treating it as a gate script would
  // collapse the table into six rows naming the lanes and lose every per-gate note.
  'verify.sh',
  'check-live-test-scripts.sh',
  'docker-build.sh',
  'docker-smoke.sh',
  'docker-wait.sh',
];

function discoverGates(): string[] {
  // Enumerated rather than hardcoded so a new scripts/ci entry forces a decision instead of being
  // silently omitted from a table the docs describe as covering scripts/ci/*.sh.
  for (const file of readdirSync(join(ROOT, 'scripts/ci')))
    if (file.endsWith('.sh') && !GATE_SCRIPTS.includes(file) && !NON_GATE_SCRIPTS.includes(file))
      fail(`scripts/ci/${file} is classified as neither a gate nor a non-gate in gen.ts`);
  const gates = GATE_SCRIPTS.flatMap((file) => scriptCommands(`scripts/ci/${file}`));
  const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
  // The container job runs the same two scripts as `ci:container`; represent it by the local command
  // so the gate list stays derived from package.json rather than from provider YAML.
  if (pkg.scripts?.['ci:container']) gates.push('bun run ci:container');
  return gates;
}

function renderGates(gates: string[]): string {
  requireExactCoverage('CI gate', gates, CI_GATE_NOTES);
  const rows = gates.map((gate) => `| \`${gate}\` | ${cell(CI_GATE_NOTES[gate] ?? '')} |`);
  return [BANNER, '', '| Gate | What it protects |', '| --- | --- |', ...rows, ''].join('\n');
}

// -------------------------------------------------------- platform settings

function renderSettings(): string {
  const keys = [...SETTING_KEYS] as string[];
  requireExactCoverage('platform setting', keys, PLATFORM_SETTING_NOTES);
  // Field-by-field defaults, not an object default: a note present but shaped wrong has already
  // been reported by the coverage check, and rendering must stay total so that error is what the
  // caller sees instead of a TypeError from this line.
  const rows = keys.map((key) => {
    const note = PLATFORM_SETTING_NOTES[key];
    return `| \`${key}\` | ${cell(note?.bounds ?? '')} | ${cell(note?.fallback ?? '')} | ${cell(note?.effect ?? '')} |`;
  });
  return [
    BANNER,
    '',
    '| Setting | Accepted values | Fallback | Effect |',
    '| --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

// ----------------------------------------------------------- dashboard menu

/**
 * One table per menu group, in the order the sidebar renders them. The group headings and page
 * labels come from `PANELS`, so a renamed or added panel changes the published table; only the
 * "what question does this page answer" sentence is hand-written.
 */
function renderDashboardMenu(): string {
  const paths = PANELS.map((panel) => panel.path);
  requireExactCoverage('dashboard panel', paths, DASHBOARD_PANEL_NOTES);
  const lines: string[] = [BANNER, ''];
  const groups = [...new Set(PANELS.map((panel) => panel.group))];
  for (const group of groups) {
    lines.push(`## ${group}`, '', '| Page | Answers |', '| --- | --- |');
    for (const panel of PANELS.filter((entry) => entry.group === group)) {
      const note = DASHBOARD_PANEL_NOTES[panel.path];
      lines.push(`| [${cell(panel.label)}](${note?.page ?? ''}) | ${cell(note?.answers ?? '')} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

// ---------------------------------------------------------- connector tools

interface ToolRow {
  name: string;
  description: string;
}

type CatalogFactory = { create?: (config: unknown) => { tools?: () => ToolRow[] } };

function toolsFor(type: string, settings: Record<string, unknown>): ToolRow[] {
  const definition = CONNECTOR_DEFINITIONS.find((entry) => entry.type === type) as
    CatalogFactory | undefined;
  if (!definition?.create) throw new Error(`no connector factory registered for "${type}"`);
  const connector = definition.create({
    id: '00000000-0000-4000-8000-000000000000',
    name: 'documentation',
    tenantId: '00000000-0000-4000-8000-000000000001',
    type,
    settings,
    getCredential: async () => '',
    repositories: {
      resolve: async () => [],
      search: async () => [],
      recentEvents: async () => [],
    },
  });
  if (typeof connector.tools !== 'function')
    throw new Error(`the "${type}" factory returned no tools() port`);
  return connector.tools();
}

function renderConnectorTools(): { partials: Record<string, string>; total: number } {
  const partials: Record<string, string> = {};
  let total = 0;

  // A shape for a removed connector would otherwise sit in notes.ts unread, since shapes are only
  // ever looked up by a type that still exists.
  for (const type of Object.keys(CONNECTOR_SHAPES))
    if (!CONNECTOR_DEFINITIONS.some((definition) => definition.type === type))
      fail(`connector shape "${type}" has a note in notes.ts but no longer exists`);
  for (const type of TOOLLESS_CONNECTORS)
    if (!CONNECTOR_DEFINITIONS.some((definition) => definition.type === type))
      fail(`toolless connector "${type}" is allowlisted in notes.ts but no longer exists`);

  for (const definition of CONNECTOR_DEFINITIONS) {
    const type = definition.type;
    const hasFactory = typeof (definition as { create?: unknown }).create === 'function';
    const lines: string[] = [BANNER, ''];

    if (!hasFactory) {
      lines.push(
        `\`${type}\` is registered in the catalog for its product metadata and has no runtime factory, so it exposes no triage tools.`,
        '',
      );
      partials[type] = lines.join('\n');
      continue;
    }

    const shapes = CONNECTOR_SHAPES[type] ?? [{ label: '', settings: {} }];
    const signatures: string[] = [];
    for (const shape of shapes) {
      const tools = toolsFor(type, shape.settings);
      total += tools.length;
      signatures.push(tools.map((tool) => tool.name).join(','));
      if (shape.label) lines.push(`**${shape.label}** — ${tools.length} tools.`, '');
      if (tools.length === 0) {
        if (!TOOLLESS_CONNECTORS.has(type))
          fail(`connector "${type}" enumerated zero tools — enumeration is broken`);
        lines.push('This connector exposes no triage tools.', '');
        continue;
      }
      lines.push('| Tool | What it does |', '| --- | --- |');
      for (const tool of tools) lines.push(`| \`${tool.name}\` | ${cell(tool.description)} |`);
      lines.push('');
    }
    // Two shapes that enumerate the same tools mean the settings key that used to select between
    // them has been renamed, so one of the tables now describes the wrong deployment.
    if (new Set(signatures).size !== signatures.length)
      fail(`connector "${type}" declares shapes in notes.ts that enumerate identical tool sets`);
    partials[type] = lines.join('\n');
  }

  // Complements the per-connector zero check, which cannot see a partial loss: a connector dropping
  // from 14 tools to 1 clears that check but not this one.
  if (total < MIN_TOTAL_CONNECTOR_TOOLS)
    fail(
      `connector tool enumeration produced ${total} tools, below the ${MIN_TOTAL_CONNECTOR_TOOLS} floor`,
    );
  return { partials, total };
}

// ------------------------------------------------------------------ writing

const outputs = new Map<string, string>();

function emit(path: string, body: string): void {
  outputs.set(path, body.endsWith('\n') ? body : `${body}\n`);
}

/**
 * Replaces the body of a named marker block inside an existing hand-written file.
 *
 * @param path - Repo-relative file carrying the markers.
 * @param name - Marker name, as in `<!-- BEGIN generated:name -->`.
 * @param body - Replacement content.
 */
function emitBlock(path: string, name: string, body: string): void {
  const absolute = join(ROOT, path);
  const source = outputs.get(path) ?? readFileSync(absolute, 'utf8');
  const begin = `<!-- BEGIN generated:${name} -->`;
  const end = `<!-- END generated:${name} -->`;
  const start = source.indexOf(begin);
  const stop = source.indexOf(end);
  if (start === -1 || stop === -1 || stop < start) {
    fail(`${path} is missing the ${begin} / ${end} markers`);
    return;
  }
  if (start !== source.lastIndexOf(begin) || stop !== source.lastIndexOf(end)) {
    fail(`${path} contains more than one ${begin} / ${end} pair`);
    return;
  }
  outputs.set(
    path,
    `${source.slice(0, start + begin.length)}\n${body.trim()}\n${source.slice(stop)}`,
  );
}

function main(): void {
  const check = process.argv.includes('--check');

  // Rendered once and reused: each render runs the coverage check, so rendering a second time for
  // the CLAUDE.md block would report every missing note twice.
  const workspaces = renderWorkspaces(discoverWorkspaces());
  const gates = renderGates(discoverGates());

  emit('docs/_generated/workspaces.md', workspaces);
  emit('docs/_generated/platform-settings.md', renderSettings());
  emit('docs/_generated/dashboard-menu.md', renderDashboardMenu());
  const { partials, total } = renderConnectorTools();
  for (const [type, body] of Object.entries(partials))
    emit(`docs/_generated/connector-tools/${type}.md`, body);

  emit('docs/_generated/ci-gates.md', gates);
  emitBlock('CLAUDE.md', 'workspaces', workspaces);
  emitBlock('CLAUDE.md', 'ci-gates', gates);
  emitBlock('CONTRIBUTING.md', 'ci-gates', gates);

  // A partial the generator no longer produces would otherwise stay committed and keep rendering
  // through its `--8<--` include, with both gates green.
  const generatedRoot = join(ROOT, 'docs/_generated');
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const child = join(dir, entry.name);
      if (entry.isDirectory()) walk(child);
      // Only the generator's own artifact type: an editor or OS scratch file is not an orphan.
      else if (entry.name.endsWith('.md') && !outputs.has(relative(ROOT, child)))
        fail(`${relative(ROOT, child)} is no longer generated — delete it`);
    }
  };
  if (existsSync(generatedRoot)) walk(generatedRoot);

  if (problems.length > 0) {
    for (const problem of problems) console.error(`error: ${problem}`);
    process.exitCode = 1;
    return;
  }

  let stale = 0;
  for (const [path, body] of outputs) {
    const absolute = join(ROOT, path);
    const current = existsSync(absolute) ? readFileSync(absolute, 'utf8') : null;
    if (current === body) continue;
    stale += 1;
    if (check) {
      console.error(`error: ${path} is out of date — run \`bun run docs:gen\``);
      continue;
    }
    mkdirSync(dirname(absolute), { recursive: true });
    writeFileSync(absolute, body);
    console.log(`wrote ${relative(ROOT, absolute)}`);
  }

  if (check && stale > 0) {
    process.exitCode = 1;
    return;
  }
  console.log(
    check
      ? `generated documentation is up to date (${outputs.size} outputs, ${total} connector tools).`
      : `done (${outputs.size} outputs, ${total} connector tools).`,
  );
}

main();
