-- Generated by drizzle-kit. The tenant slug update is a required data backfill that schema
-- generation cannot express.
CREATE TABLE "identity_provider_domains" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider_id" uuid NOT NULL,
	"domain" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"challenge" text,
	"verified_at" timestamp with time zone,
	"last_checked_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "identity_provider_domains_provider_id_domain_unique" UNIQUE("provider_id","domain"),
	CONSTRAINT "identity_provider_domains_status_check" CHECK (status in ('pending','verified','failed'))
);
--> statement-breakpoint
CREATE TABLE "identity_providers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"display_name" text NOT NULL,
	"issuer" text NOT NULL,
	"jwks_uri" text NOT NULL,
	"authorization_endpoint" text,
	"token_endpoint" text,
	"audience" text NOT NULL,
	"kind" text NOT NULL,
	"scope" text NOT NULL,
	"supports_signup" boolean DEFAULT false NOT NULL,
	"email_claim" text DEFAULT 'email' NOT NULL,
	"tenant_claim" text,
	"subject_claim" text DEFAULT 'sub' NOT NULL,
	"browser_client_id" text,
	"status" text NOT NULL,
	"expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "identity_providers_kind_check" CHECK (kind in ('oidc','local')),
	CONSTRAINT "identity_providers_scope_check" CHECK (scope in ('installation','tenant')),
	CONSTRAINT "identity_providers_status_check" CHECK (status in ('provisional','pending_verification','active','disabled','failed'))
);
--> statement-breakpoint
CREATE TABLE "platform_admin_invitations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"issuer" text NOT NULL,
	"email" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"accepted_at" timestamp with time zone,
	"accepted_user_id" uuid,
	CONSTRAINT "platform_admin_invitations_issuer_email_unique" UNIQUE("issuer","email")
);
--> statement-breakpoint
CREATE TABLE "tenant_identity_bindings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"provider_id" uuid NOT NULL,
	"claim_value" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tenant_identity_bindings_provider_id_claim_value_unique" UNIQUE NULLS NOT DISTINCT("provider_id","claim_value")
);
--> statement-breakpoint
CREATE TABLE "tenant_invitations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"email" text NOT NULL,
	"role" text DEFAULT 'member' NOT NULL,
	"invited_by_user_id" uuid NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"provider_invitation_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "tenant_invitations_role_check" CHECK (role in ('admin','member')),
	CONSTRAINT "tenant_invitations_status_check" CHECK (status in ('pending','accepted','revoked','expired'))
);
--> statement-breakpoint
CREATE TABLE "workspace_foundings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"path" text NOT NULL,
	"slug" text NOT NULL,
	"requested_name" text NOT NULL,
	"provider_id" uuid,
	"founder_user_id" uuid,
	"declared_domain" text,
	"status" text NOT NULL,
	"claim_value" text,
	"tenant_id" uuid,
	"failure_reason" text,
	"terms_accepted_version" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone,
	CONSTRAINT "workspace_foundings_slug_unique" UNIQUE("slug"),
	CONSTRAINT "workspace_foundings_path_check" CHECK (path in ('hosted','own_directory')),
	CONSTRAINT "workspace_foundings_status_check" CHECK (status in ('awaiting_founder','founder_authenticated','pending','approved','provisioning','active','failed','rejected','expired'))
);
--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN "role" text DEFAULT 'member' NOT NULL;--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN "status" text DEFAULT 'active' NOT NULL;--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "tenants" ADD COLUMN "slug" text;--> statement-breakpoint
UPDATE "tenants" SET "slug" = 'workspace-' || "id"::text WHERE "slug" IS NULL;--> statement-breakpoint
ALTER TABLE "tenants" ALTER COLUMN "slug" SET DEFAULT 'workspace-' || gen_random_uuid()::text;--> statement-breakpoint
ALTER TABLE "tenants" ALTER COLUMN "slug" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "tenants" ADD COLUMN "status" text DEFAULT 'active' NOT NULL;--> statement-breakpoint
ALTER TABLE "tenants" ADD COLUMN "delete_after" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "status" text DEFAULT 'active' NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "last_sign_in_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "not_before" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "identity_provider_domains" ADD CONSTRAINT "identity_provider_domains_provider_id_identity_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."identity_providers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform_admin_invitations" ADD CONSTRAINT "platform_admin_invitations_accepted_user_id_users_id_fk" FOREIGN KEY ("accepted_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tenant_identity_bindings" ADD CONSTRAINT "tenant_identity_bindings_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tenant_identity_bindings" ADD CONSTRAINT "tenant_identity_bindings_provider_id_identity_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."identity_providers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tenant_invitations" ADD CONSTRAINT "tenant_invitations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tenant_invitations" ADD CONSTRAINT "tenant_invitations_invited_by_user_id_users_id_fk" FOREIGN KEY ("invited_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_foundings" ADD CONSTRAINT "workspace_foundings_provider_id_identity_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."identity_providers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_foundings" ADD CONSTRAINT "workspace_foundings_founder_user_id_users_id_fk" FOREIGN KEY ("founder_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_foundings" ADD CONSTRAINT "workspace_foundings_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "identity_provider_domains_verified_idx" ON "identity_provider_domains" USING btree (lower("domain")) WHERE "identity_provider_domains"."status" = 'verified';--> statement-breakpoint
CREATE UNIQUE INDEX "identity_providers_active_issuer_idx" ON "identity_providers" USING btree ("issuer") WHERE "identity_providers"."status" = 'active';--> statement-breakpoint
ALTER TABLE "tenants" ADD CONSTRAINT "tenants_slug_unique" UNIQUE("slug");--> statement-breakpoint
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_role_check" CHECK (role in ('owner','admin','member'));--> statement-breakpoint
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_status_check" CHECK (status in ('active','removed'));--> statement-breakpoint
ALTER TABLE "tenants" ADD CONSTRAINT "tenants_status_check" CHECK (status in ('active','suspended','deleting'));--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_status_check" CHECK (status in ('active','disabled','deleted'));
