import { GitHubInstallationDiscoveryError } from '@sre/connectors';
import { createHash } from 'node:crypto';

export function failureCategory(result: {
  reachable: boolean;
  authorized: boolean;
  checks?: Record<string, boolean>;
  failureCategory?: string;
}): string | null {
  if (result.failureCategory) return result.failureCategory;
  if (!result.reachable) return 'unreachable';
  if (!result.authorized || Object.values(result.checks ?? {}).includes(false))
    return 'permission_denied';
  return 'provider_unavailable';
}

export function githubInstallationDiscoveryFailure(error: unknown): {
  status: 400 | 422 | 429 | 502 | 503;
  code:
    | 'invalid_private_key'
    | 'credentials_rejected'
    | 'rate_limited'
    | 'provider_unavailable'
    | 'unreachable'
    | 'invalid_response';
  message: string;
  upstreamStatus: number | null;
  rateLimitRemaining?: number;
  rateLimitResetAt?: string;
} {
  const failure =
    error instanceof GitHubInstallationDiscoveryError
      ? error
      : new GitHubInstallationDiscoveryError('invalid_response');
  const details = {
    upstreamStatus: failure.upstreamStatus,
    ...(failure.rateLimit.remaining !== undefined
      ? { rateLimitRemaining: failure.rateLimit.remaining }
      : {}),
    ...(failure.rateLimit.resetAt ? { rateLimitResetAt: failure.rateLimit.resetAt } : {}),
  };
  switch (failure.failureCategory) {
    case 'invalid_private_key':
      return {
        status: 400,
        code: failure.failureCategory,
        message:
          'The private key is not a valid GitHub App PEM file. Generate a new private key and paste the complete file.',
        ...details,
      };
    case 'credentials_rejected':
      return {
        status: 422,
        code: failure.failureCategory,
        message:
          'GitHub rejected this client/App ID and private key. Confirm the key was generated by the same GitHub App.',
        ...details,
      };
    case 'rate_limited':
      return {
        status: 429,
        code: failure.failureCategory,
        message: 'GitHub rate limited installation discovery. Retry after the reset time.',
        ...details,
      };
    case 'provider_unavailable':
      return {
        status: 503,
        code: failure.failureCategory,
        message: 'GitHub is unavailable. Retry installation discovery shortly.',
        ...details,
      };
    case 'unreachable':
      return {
        status: 502,
        code: failure.failureCategory,
        message: 'SRE Platform could not reach GitHub. Check network access and retry.',
        ...details,
      };
    case 'invalid_response':
      return {
        status: 502,
        code: failure.failureCategory,
        message: 'GitHub returned an unexpected response during installation discovery.',
        ...details,
      };
  }
}

export const GITHUB_MANIFEST_TTL_MS = 60 * 60 * 1000;
export const GITHUB_APP_EVENTS = [
  'push',
  'pull_request',
  'workflow_run',
  'deployment',
  'deployment_status',
  'repository',
] as const;

export function manifestStateHash(state: string): string {
  return createHash('sha256').update(state).digest('hex');
}

export function externalUrl(input: unknown, allowLocalHttp = false): URL | null {
  if (typeof input !== 'string' || input.length > 2048) return null;
  try {
    const url = new URL(input);
    if (url.username || url.password || url.search || url.hash) return null;
    const local = url.hostname === 'localhost' || url.hostname === '127.0.0.1';
    if (url.protocol !== 'https:' && !(allowLocalHttp && local && url.protocol === 'http:'))
      return null;
    return url;
  } catch {
    return null;
  }
}

export function githubAppOwnerPath(ownerType: string, organization?: string): string | null {
  if (ownerType === 'personal') return 'https://github.com/settings/apps/new';
  if (
    ownerType !== 'organization' ||
    !organization ||
    !/^[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?$/.test(organization)
  )
    return null;
  return `https://github.com/organizations/${encodeURIComponent(organization)}/settings/apps/new`;
}

/** Tenant-facing CRUD for connector configs. Settings live in Postgres (RLS); the
 *  credential is encrypted via the SecretStore and never returned. */
