// Local copy is deliberate: provider and proxy response text is not a presentation contract.
export const GITHUB_DISCOVERY_ERRORS: Readonly<Record<string, string>> = {
  invalid_private_key:
    'The private key is not a valid GitHub App PEM file. Generate a new private key and paste the complete file.',
  credentials_rejected:
    'GitHub rejected this client/App ID and private key. Confirm the key was generated by the same GitHub App.',
  rate_limited: 'GitHub rate limited installation discovery. Retry after the reset time.',
  provider_unavailable: 'GitHub is unavailable. Retry installation discovery shortly.',
  unreachable: 'SRE Platform could not reach GitHub. Check network access and retry.',
  invalid_response: 'GitHub returned an unexpected response during installation discovery.',
};

export const GITLAB_DISCOVERY_ERRORS: Readonly<Record<string, string>> = {
  authentication: 'GitLab rejected the token. Check its expiry and whether it has been revoked.',
  permission: 'GitLab denied access. Check read_api scope and Reporter access to the group.',
  not_found:
    'GitLab could not find an accessible group or project. Check the full group path and token membership. Personal namespaces are not groups.',
  rate_limit: 'GitLab is rate limiting discovery. Wait before trying again.',
  unavailable: 'GitLab is temporarily unavailable. Try again shortly.',
  timeout:
    'GitLab did not respond in time. Check connectivity from the SRE Platform API, then retry.',
  network:
    'The SRE Platform API could not connect to GitLab. Check DNS, TLS certificates, and network access.',
  response_limit:
    'The GitLab catalog or response exceeds the discovery safety limit. Choose a smaller operational group.',
  unsafe_url:
    'The GitLab address is blocked by the connector URL policy. Use a permitted HTTPS instance address.',
  invalid_response:
    'GitLab returned an unexpected response. Check the instance URL and any proxy in front of GitLab.',
  unknown:
    'GitLab discovery could not complete. Retry, or ask your administrator to check the diagnostic reference.',
};
